App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']